### ISSUE TITLE
Make minsdk smaller

### ISSUE THREAD

**Issue by guliash** [AzimoLabs/ConditionWatcher#5]
Thank you for this nice approach to ui testing.

Could you please make minsdk smaller? 16 is too strict.

**Comment by FisherKK** [comment]
Hey @guliash 

Sorry I agree that there are some things to be improved and fixed. Thank you for pointing that.
I will generate new 0.2 version and update it tomorrow morning for sure.

**Comment by FisherKK** [comment]
Hey @guliash 
It's done.

**Comment by guliash** [comment]
Wow! Thank you very much!
